//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Transport_Counter
    {
        public int Id { get; set; }
        public int User_Id { get; set; }
        public int T_Id { get; set; }
        public int Count { get; set; }
    
        public virtual User User { get; set; }
    }
}
